### ISSUE TITLE
Highlight all neumes in system

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/neon2-wrapper#5]
By clicking on a system, all musical elements (i.e., neumes, custos, clef, division, etc.) belonging to that system should be highlighted.

The goal of this highlighting tool is allowing the user to visually inspect if all elements are actually part, and rendered, in the chosen system.

**Comment by JRegimbal** [comment]
Staff highlighting added in DDMAL/Neon2#93. It provides a toggle to highlight each system along with all its musical elements in different colors. (This can also be seen by using staff selection, added in DDMAL/Neon2#113, but this only can highlight one system at a time.)
